version: '3'
services:
  db:
    container_name: docker-mysql
    image: mysql:5.6
    restart: always
    env_file: .env
    environment: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Tokyo"
    ports: 
      - "3308:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
      - db-volume:/var/lib/mysql

volumes:
  db-volume: